security:
    acl:
        connection: default
    encoders:
        user_provider:
             class: MD\Bundle\UserBundle\Entity\Account
             algorithm: bcrypt
             cost:      15
        Symfony\Component\Security\Core\User\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
        
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_CONTRACTING_MANAGER:   [ROLE_USER ,ROLE_Content_Data_Entry,ROLE_Content_Settings]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN,ROLE_Content_Data_Entry,ROLE_Content_Settings, ROLE_CONTRACTING_MANAGER , ROLE_ALLOWED_TO_SWITCH ]

    providers:
      user_provider:
        chain:
          providers: [in_memory, db]
      in_memory:
        memory:
            users:
              super@admin.pn: { password: 0f77d4f39eb84f9e5724a759767690971354b73d , roles: [ 'ROLE_SUPER_ADMIN' ] }
      db:
        entity: 
          class: UserBundle:Account 
          property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        members_secured_area:
            pattern: /.*
            provider: user_provider
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login
                success_handler: authentication_handler
                default_target_path: dashboard
            logout:
                path:   /logout
                target: /login
    
    access_control:
        - { path: ^/user, roles: ROLE_SUPER_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
